### ISSUE TITLE
TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by longzhou123** [win5do/vue-admin#5]
TypeError: Cannot read property 'length' of null
    at func.connPool.rows (E:\vue-fb-demo\back-end\controls\user.js:90:23)
    at Query.conn.query [as _callback] (E:\vue-fb-demo\back-end\sql\func.js:16:17)
    at Query.Sequence.end (E:\vue-fb-demo\back-end\node_modules\mysql\lib\protocol\sequences\Sequence.js:88:24)
    at Query._handleFinalResultPacket (E:\vue-fb-demo\back-end\node_modules\mysql\lib\protocol\sequences\Query.js:139:8)
    at Query.EofPacket (E:\vue-fb-demo\back-end\node_modules\mysql\lib\protocol\sequences\Query.js:123:8)
    at Protocol._parsePacket (E:\vue-fb-demo\back-end\node_modules\mysql\lib\protocol\Protocol.js:279:23)
    at Parser.write (E:\vue-fb-demo\back-end\node_modules\mysql\lib\protocol\Parser.js:76:12)
    at Protocol.write (E:\vue-fb-demo\back-end\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\vue-fb-demo\back-end\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:116:13)

**Comment by stayhungrystayfoollish** [comment]
fetchById (req, res) {
        let id = req.body.id;

        func.connPool(sql.queryById, ['goods', id], rows => {
            rows = formatData(rows);
            res.json({code: 200, msg: 'ok', goods: rows[0]});
        });

    },



所有的 rows 改为 (err, rows)
修改后
 fetchById (req, res) {
        let id = req.body.id;

        func.connPool(sql.queryById, ['goods', id], (err, rows)=> {_
            rows = formatData(rows);
            res.json({code: 200, msg: 'ok', goods: rows[0]});
        });

    },
